# kotaemon使用说明

## 环境配置

```sh
pip install -e "libs/kotaemon[all]"
pip install -e "libs/ktem"
pip install graphrag future
pip install git+https://github.com/HKUDS/LightRAG.git
pip install nano-graphrag
```

## 使用方式

```sh
python app.py
```

输出目录：ktem_app_data
用户数据目录：ktem_app_data/user_data
markdown输出目录：ktem_app_data/markdown_cache_dir
chunks输出目录：ktem_app_data/chunks_cache_dir
zip输出目录：ktem_app_data/zip_cache_dir
zip输入目录：ktem_app_data/zip_cache_dir_in

## 修改过程

先成功跑通索引：

在flowsettings.py中添加有关BGEEmbedding的相关设置；

```python
KH_EMBEDDINGS["bge"] = {
    "spec": {
        "__type__": "kotaemon.embeddings.LCBGEEmbeddings",
        # "model_name": "/Users/wuzm/Documents/CodeRepository/Models/embedding_models/bge-m3",
        "model_name": "E:/Models/embedding/bge-m3",
    },
    "default": not IS_OPENAI_DEFAULT,
}
```

在kotaemon/embeddings/langchain_base.py中添加有关BGE的类；

```python
class LCBGEEmbeddings(LCEmbeddingMixin, BaseEmbeddings):
    """Wrapper around Langchain's BGE embedding, focusing on key parameters"""

    model_name: str = Param(
        help="Model name to use (https://ai.google.dev/gemini-api/docs/models/gemini#text-embedding-and-embedding)",  # noqa
        default="models/text-embedding-004",
        required=True,
    )

    def __init__(
        self,
        model_name: str = "models/text-embedding-004",
        model_kwargs: dict = {'device': 'cpu'},
        encode_kwargs: dict = {'normalize_embeddings': False},
        **params,
    ):
        super().__init__(
            model_name=model_name,
            model_kwargs=model_kwargs,
            encode_kwargs=encode_kwargs,
            **params,
        )

    def _get_lc_class(self):
        try:
            from langchain_community.embeddings import HuggingFaceBgeEmbeddings
        except ImportError:
            raise ImportError("Please install langchain_community")

        return HuggingFaceBgeEmbeddings
```

跑通大模型回答

在flowsettings.py中添加有关QWEN大模型的设置；

在kotaemon/llm/chats/langchain_base.py中添加有关BGE的类；

## 问题

ValueError: Cannot create index "File Collection": type object 'hnswlib.Index' has no attribute 'file_handle_count'

解决方法：删掉保存目录，重新运行程序；

ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True or check your proxy settings to allow access to localhost.

解决方法：

```sh
pip install pydantic==2.10.6
```
